services:
  mysql:
    image: mysql:8.0
    container_name: youchallenge1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: youchallenge
      MYSQL_USER: admin@admin.com
      MYSQL_PASSWORD: root_password
    ports:
      - "3309:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: youchallenge_admin
    restart: always
    environment:
      PMA_HOST: mysql  # Make sure this is set to the correct service name
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "8089:80"
    networks:
      - laravel_network  # Ensure both services are on the same network

  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: youchallenge
    restart: always
    working_dir: /var/www/html
    volumes:
      - ./project:/var/www/html
    ports:
      - "8889:80"
    depends_on:
      - mysql
    networks:
      - laravel_network

volumes:
  db_data:

networks:
  laravel_network:
    driver: bridge
